<?php

declare(strict_types=1);

return [
    'title_max_chars' => 120,
    'row_text_max_chars' => 500,
    'max_rows' => 5,
    'min_requested_count' => 1,
    'max_requested_count' => 10,
    'max_total_requested' => 10,
    'max_advanced_total_requested' => 30,
    'processing_lease_seconds' => 120,
    'queued_abandonment_seconds' => 900,
    'job_timeout_seconds' => 270,
    'provider_http_timeout_seconds' => 60,
    'provider_connect_timeout_seconds' => 10,
    'max_provider_attempts' => 3,
    'new_fills_per_hour' => 3,
    'throttle_window_seconds' => 3_600,
    'stale_recovery_batch_size' => 50,
    'queue_connection' => env('QUESTION_BLUEPRINT_QUEUE_CONNECTION', 'database-generation'),
    'queue' => env('QUESTION_BLUEPRINT_QUEUE', 'material-intelligence'),
    'api_key' => env('GEMINI_API_KEY'),
    'api_base' => env('QUESTION_BLUEPRINT_API_BASE', 'https://generativelanguage.googleapis.com/v1beta'),
    'primary_model' => env('QUESTION_BLUEPRINT_PRIMARY_MODEL', 'gemini-3.5-flash-lite'),
    'prompt_version' => env('QUESTION_BLUEPRINT_PROMPT_VERSION', 'blueprint-fill-v1'),
    'advanced_prompt_version' => env('QUESTION_BLUEPRINT_ADVANCED_PROMPT_VERSION', 'blueprint-fill-v2'),
    'multitype_prompt_version' => env('QUESTION_BLUEPRINT_MULTITYPE_PROMPT_VERSION', 'blueprint-fill-v3'),
    'max_output_tokens' => (int) env('QUESTION_BLUEPRINT_MAX_OUTPUT_TOKENS', 4096),
    'backoff_seconds' => [5, 15],
    'status_poll_interval_ms' => 5_000,
    'run_item_span_max_chars' => 16_000,

    'max_profile_elements' => 40,
    'max_chunk_refs' => 12,
    'max_chars_per_context' => 400,
    'max_total_context_chars' => 3_200,
    'max_serialized_request_chars' => 16_000,
    'max_contexts_per_row' => 4,

    'import_structure_schema_version' => 'blueprint-import-structure-v1',
    'import_structure_max_blocks' => 500,
    'import_structure_max_tables' => 50,
    'import_structure_max_rows' => 500,
    'import_structure_max_cells' => 5000,
    'import_structure_max_paragraphs_per_cell' => 50,
    'import_structure_max_cell_chars' => 8000,

    'import_interpretation_prompt_version' => 'blueprint-import-interpret-v1',
    'import_interpretation_max_request_bytes' => 262_144,
    'max_import_candidates' => 100,
    'import_interpretation_stale_seconds' => 330,
    'import_interpretation_max_output_tokens' => 16_384,

    'import_grounding_prompt_version' => 'blueprint-import-ground-v1',
    'import_grounding_max_catalog_elements' => 200,
    'import_grounding_max_request_bytes' => 262_144,
    'import_grounding_max_refs_per_claim' => 4,
    'import_grounding_stale_seconds' => 330,
    'import_grounding_max_output_tokens' => 16_384,
];
